name: "Bug Report"
description: Something is not working correctly.
title: "[BUG] "
labels: [
  "bug"
]
assignees: "SplendidAlakey"
body:
  - type: dropdown
    id: version
    attributes:
      label: "Perfectly Splendid version"
      description: What version of Perfectly Splendid are you playing on?
      multiple: false
      options:
        - 0.1
    validations:
      required: true
  - type: dropdown
    id: launcher
    attributes:
      label: "Launcher"
      description: What launcher are you using?
      multiple: false
      options:
        - Prism Launcher
        - Vanilla launcher
        - MultiMC
        - CurseForge app
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What OS are you on?
      multiple: false
      options:
        - Windows
        - Linux
        - Mac
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe exactly what you are having issues with
      placeholder: When I smelt ores in a diamond furnace, it takes too long...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Describe how can the bug be reproduced
      placeholder: 
        1. Put raw iron ore in a diamond furnace
        2. Start smelting
        3. Notice the time it takes
        4. ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drop your screenshots here.
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copy your logs from .minecraft/logs/latest.log or .minecraft/crash-reports to a paste service like mclo.gs or GitHub Gists and paste it here.
    validations:
      required: true
  - type: textarea
    id: adds
    attributes:
      label: "Additional context"
      description: If you added any extra mods or changed any settings, please list it here
      placeholder: I did not add or change anything.
    validations:
      required: false
