blank_issues_enabled: false
contact_links:
  - name: Perfectly Splendid questions
    url: https://github.com/SplendidAlakey/Perfectly-Splendid/discussions/3
    about: Check this Q&A before asking any questions.
  - name: Splendid questions
    url: https://github.com/SplendidAlakey/Perfectly-Splendid/discussions/
    about: If you didn't find an answer to your question, either create a new discussion or make a comment in the Q&A thread.
