blank_issues_enabled: true
contact_links:
  - name: Perfectly Splendid F.A.Q.
    url: https://github.com/SplendidAlakey/Perfectly-Splendid/wiki/F.A.Q.
    about: Check this F.A.Q. before opening a blank issue.