name: Crash report
about: Minecraft crashes when playing Perfectly Splendid
title: "[CRASH] "
labels: 1.19.2, crash
assignees: Footage2-Amply-Pounce
body: 
  - type: checkboxes
    attributes:
        label: Make sure that your issue is unique and fitting! Duplicates and offtopic issues will be closed.
        multiple: true
        options:
  - label: I made sure that my issue is unique and has not been posted before.
  - label: My issue is about Perfectly Splendid MC Modpack and/or its included mods.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Minecraft version (required)
      description: What is the Minecraft version you are playing with?
      options:
        - "1.19.2"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Perfectly Splendid Version (required)
      description: What version of the modpack are you using?
      options:
        - "0.1"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Launcher (required)
      description: What launcher are you using?
      options:
        - Prism Launcher
        - MultiMC
        - CurseForge app
        - Vanilla launcher
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: OS (required)
      description: What OS are you using?
      placeholder: Windows 11
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description (required)
      description: A clear and concise description of what you did prior to the crash.
      placeholder: 
        _example_: When I kill a cow with a modded weapon, the game crashes.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce, if possible (optional)
      description: Describe exactly how to reproduce the crash.
      placeholder: 
        _example_: **To Reproduce:**

1. 
2. 
3. 
4. 

    validations:
      required: false

    - type: textarea
      attributes:
        label: Screenshots and Videos (optional)
        description: If applicable, add screenshots/videos to help explain your problem.
     validations:
      required: false
      
    - type: textarea
      attributes:
        label: Logs
        description: Navigate to .minecraft/logs, as well as .minecraft/crash-reports, copy the contents of a file called latest.log, paste it to a site like mclo.gs or GitHub Gists.
     validations:
      required: true
      
    - type: textarea
      attributes:
        label: Additional context
        description: If you installed any additional mods and/or changed any settings, list it here.
     validations:
      required: false
