name: "Crash Report"
description: The game crashes when playing Perfectly Splendid.
title: "[CRASH] "
labels: [
  "crash"
]
assignees: "SplendidAlakey"
body:
  - type: dropdown
    id: version
    attributes:
      label: "Perfectly Splendid version"
      description: What version of Perfectly Splendid are you playing on?
      multiple: false
      options:
        - -
        - 1.1.2.0
        - 1.1.1.0
        - 1.1.0.0
        - 1.0.1.1
        - 1.0.1.0
        - 1.0.0.0
        - 0.9
        - 0.8
        - 0.7
        - 0.6
        - 0.5
        - 0.4
        - 0.31
        - 0.3
        - 0.2
        - 0.1
    validations:
      required: true
  - type: dropdown
    id: launcher
    attributes:
      label: "Launcher"
      description: What launcher are you using?
      multiple: false
      options:
        - -
        - Prism Launcher
        - Vanilla launcher
        - MultiMC
        - CurseForge app
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What OS are you on?
      multiple: false
      options:
        - -
        - Windows
        - Linux
        - Mac
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe exactly what were you doing prior to the game crash.
      placeholder: I was in the Nether and I died while fighting a wither skeleton...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Describe how can the crash be reproduced.
      placeholder: 
        1. Go to the Nether
        
        2. Find a wither skeleton
        
        3. Take damage from it until you die
        
        4. ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copy your logs from .minecraft/logs/latest.log or .minecraft/crash-reports to a paste service like mclo.gs or GitHub Gists and paste it here.
    validations:
      required: true
  - type: textarea
    id: adds
    attributes:
      label: "Additional context"
      description: If you added any extra mods or changed any settings, please list it here
      placeholder: I did not add or change anything.
    validations:
      required: false
