name: "Suggestion"
description: I would like to propose a change or addition to the pack.
title: "[SUGGESTION] "
labels: [
  "💡 suggestion"
]
assignees: "SplendidAlakey"
body:
  - type: checkboxes
    id: check
    attributes:
      label: The suggestion is unique
      description: Make sure that your suggestion is unique
      options:
        - label: I made sure that my suggestion is unique
          required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe what you would like to add or change about Perfectly Splendid.
      placeholder: I'd like to add this cool mod _link_ !
    validations:
      required: true
