name: Suggestion
about: Suggest an addition or change to the modpack
title: "[SUGGESTION] "
labels: 0.1, 1.19.2, suggestion
assignees: SplendidAlakey
body: 
  - type: checkboxes
    attributes:
        label: Make sure that your suggestion is unique and not on the list of considered mods: https://github.com/SplendidAlakey/Perfectly-Splendid/discussions/2.
        multiple: true
        options:
  - label: I made sure that my suggestion is unique and not on the list of considered mods.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Minecraft version (required)
      description: What is the Minecraft version you are playing with?
      options:
        - "1.19.2"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Perfectly Splendid Version (required)
      description: What version of the modpack are you using?
      options:
        - "0.1"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description (required)
      description: Describe what would you like to change about the mod pack.
      placeholder: 
        _example_: Add this cool mod: _link_
    validations:
      required: true
